POST http://localhost:3000/api/todo

###
POST http://localhost:3000/api/add
Content-Type: application/json

{
    "document": {
        "text": "ok when ?"
    }
}
### 
POST http://localhost:3000/api/delete 
Content-Type: application/json

{
    "filter": { "_id": { "$oid": "64990e1f1d3a0cf2382ffd5b" } }
}